server:
  port: 8086
spring:
  application:
    name: dubbouser
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/dubbo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: chen2018
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis:
  type-aliases-package: com.dario.dubbouser
  mapper-locations: classpath:mapper/*.xml

jwt:
  secret: javainuse
  header: Authorization

dubbo:
  scan:
    base-packages: com.dario.dubbouser.service
  application:
    id: dubbouser
    name: dubbouser
  protocol:
    port: 20883
    id: dubbo
    name: dubbo
  registry:
    id: zookeeper
    address: zookeeper://192.168.187.128:2181
    client: curator
